hostkit_xs_shop_homepage:
    pattern:  /
    defaults: { _controller: HostkitShopBundle:Default:home }

hostkit_xs_shop_default:
    pattern:  /default
    defaults: { _controller: HostkitShopBundle:Default:index }

hostkit_xs_shop_hosting_overview:
    pattern:  /hosting
    defaults: { _controller: HostkitShopBundle:Hosting:index }

hostkit_xs_shop_domain_overview:
    pattern:  /domain
    defaults: { _controller: HostkitShopBundle:Domain:index }

hostkit_shop_cart_one:
    pattern:  /cart/domaincheck/{package_id}
    defaults: { _controller: HostkitShopBundle:Cart:stepOne }

hostkit_shop_cart_two:
    pattern:  /cart/package
    defaults: { _controller: HostkitShopBundle:Cart:stepTwo }

hostkit_shop_cart_three:
    pattern:  /cart/overview
    defaults: { _controller: HostkitShopBundle:Cart:stepThree }

hostkit_shop_session_data:
    pattern:  /session/data
    defaults: { _controller: HostkitShopBundle:Cart:sessionData }

hostkit_shop_order_thankyou:
    pattern:  /order/thankyou/{invoiceId}
    defaults: { _controller: HostkitShopBundle:Cart:thankyou }

hostkit_shop_support_ticket:
    pattern:  /support/add
    defaults: { _controller: HostkitShopBundle:Support:add }

hostkit_shop_faq:
    pattern:  /faq
    defaults: { _controller: HostkitShopBundle:Support:faq }

hostkit_shop_faq_detail:
    pattern:  /faq/detail/{faqId}
    defaults: { _controller: HostkitShopBundle:Support:faqDetail }

hostkit_shop_faq_category_detail:
    pattern:  /faq/category/{faqCategoryId}
    defaults: { _controller: HostkitShopBundle:Support:faqCategory }

hostkit_shop_faq_all:
    pattern:  /faq/all
    defaults: { _controller: HostkitShopBundle:Support:faqAll }

hostkit_custom_page:
    pattern:  /p/{name}
    defaults: { _controller: HostkitShopBundle:Page:index }

hostkit_paypal:
    pattern:  /paypal
    defaults: { _controller: HostkitShopBundle:Payment:paypal }

hostkit_paypal_notify:
    pattern:  /paypal/notify
    defaults: { _controller: HostkitShopBundle:Payment:paypalNotify }

hostkit_paypal_return:
    pattern:  /paypal/return
    defaults: { _controller: HostkitShopBundle:Payment:paypalReturn }

hostkit_paypal_invoice:
    pattern:  /paypal/invoice/{invoiceId}
    defaults: { _controller: HostkitShopBundle:Payment:paypalInvoice }

hostkit_paypal_invoice_notify:
    pattern:  /paypal/notify/invoice
    defaults: { _controller: HostkitShopBundle:Payment:paypalNotifyInvoice }