parameters:
#    hostkit_xs_core.example.class: Hostkit\CoreBundle\Example

services:
#    hostkit_xs_core.example:
#        class: %hostkit_xs_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
