hostkit_xs_server_overview:
    pattern:  /server
    defaults: { _controller: HostkitAdminBundle:Server\Default:index }

hostkit_xs_server_add:
    pattern:  /server/add
    defaults: { _controller: HostkitAdminBundle:Server\Default:add }

hostkit_xs_server_modify:
    pattern:  /server/modify/{serverId}
    defaults: { _controller: HostkitAdminBundle:Server\Default:modify }

hostkit_xs_server_delete:
    pattern:  /server/delete/{serverId}
    defaults: { _controller: HostkitAdminBundle:Server\Default:delete }

hostkit_xs_server_default:
    pattern:  /server/default/{serverId}
    defaults: { _controller: HostkitAdminBundle:Server\Default:default }