hostkit_client_invoices:
    pattern:  /invoice
    defaults: { _controller: HostkitClientBundle:Invoice:index }

hostkit_client_invoices_pdf:
    pattern:  /invoice/pdf/{invoiceId}
    defaults: { _controller: HostkitClientBundle:Invoice:generatePdf }

hostkit_client_invoices_pdf_order:
    pattern:  /invoice/order/pdf/{orderId}
    defaults: { _controller: HostkitClientBundle:Invoice:generateOrderPdf }

hostkit_client_invoices_detail:
    pattern:  /invoice/detail/{invoiceId}
    defaults: { _controller: HostkitClientBundle:Invoice:detail }