parameters:
    avro_stripe.plan.form.type.class: Avro\StripeBundle\Form\Type\PlanFormType
    avro_stripe.plan.form.handler.class: Avro\StripeBundle\Form\Handler\PlanFormHandler

services:
    avro_stripe.stripe_plan.manager:
        class: Avro\StripeBundle\Stripe\PlanManager
        arguments: ['%avro_stripe.secret_key%']

    avro_stripe.form.handler:
        class: %avro_stripe.plan.form.handler.class%
        arguments: ["@avro_stripe.plan.form", "@request", "@event_dispatcher" ,"@avro_stripe.plan.manager", "@avro_stripe.stripe_plan.manager"]
        scope: request

    avro_stripe.plan.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["%avro_stripe.plan.form.name%", "@avro_stripe.plan.form.type"]
        scope: request

    avro_stripe.plan.form.type:
        class: %avro_stripe.plan.form.type.class%
        arguments: ["%avro_stripe.plan.class%"]
        tags: 
            - { name: form.type, alias: avro_stripe_plan }

