hostkit_xs_admin_support_tickets:
    pattern:  /support/tickets
    defaults: { _controller: HostkitAdminBundle:Support\Default:listTickets }

hostkit_xs_admin_support_ticket_reply:
    pattern:  /support/ticket/reply/{ticketId}
    defaults: { _controller: HostkitAdminBundle:Support\Default:replyTicket }

hostkit_xs_admin_support_ticket_detail:
    pattern:  /support/ticket/detail/{ticketId}
    defaults: { _controller: HostkitAdminBundle:Support\Default:detailTicket }

hostkit_xs_admin_support_ticket_close:
    pattern:  /support/ticket/close/{ticketId}
    defaults: { _controller: HostkitAdminBundle:Support\Default:closeTicket }

hostkit_xs_admin_support_department_add:
    pattern:  /support/department/add
    defaults: { _controller: HostkitAdminBundle:Support\Default:addSupportDepartment }

hostkit_xs_admin_support_faq:
    pattern:  /faq/list
    defaults: { _controller: HostkitAdminBundle:Support\Faq:index }

hostkit_xs_admin_support_faq_add:
    pattern:  /faq/add
    defaults: { _controller: HostkitAdminBundle:Support\Faq:add }

hostkit_xs_admin_support_faq_modify:
    pattern:  /faq/modify/{faqId}
    defaults: { _controller: HostkitAdminBundle:Support\Faq:modify }

hostkit_xs_admin_support_faq_delete:
    pattern:  /faq/delete/{faqId}
    defaults: { _controller: HostkitAdminBundle:Support\Faq:delete }

hostkit_xs_admin_support_faq_category_add:
    pattern:  /faq/category/add
    defaults: { _controller: HostkitAdminBundle:Support\Faq:addCategory }