hostkit_client_support:
    pattern:  /support
    defaults: { _controller: HostkitClientBundle:Support:index }

hostkit_client_support_add:
    pattern:  /support/add/{service}
    defaults: { _controller: HostkitClientBundle:Support:add, service: 0  }

hostkit_client_support_detail:
    pattern:  /support/detail/{ticketId}
    defaults: { _controller: HostkitClientBundle:Support:detail }