security:
    encoders:
        Hostkit\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_CLIENT:      ROLE_CLIENT
        #ROLE_USER: [ROLE_USER, ROLE_SUPER_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
                id: fos_user.user_manager

    firewalls:
        admin:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login_check
                use_forward:    false
            logout:
                path:   /logout
                target: /login
            anonymous: ~
        main:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login_check
                use_forward:    false
            logout:
                path:   /logout
                target: /login
            anonymous: ~

    access_control:
          - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/, role: ROLE_ADMIN }
          - { path: ^/client/, role: ROLE_CLIENT }
          - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
