hostkit_xs_cms_site_list:
    pattern:  /site/list
    defaults: { _controller: HostkitAdminBundle:CMS\Site:index }

hostkit_xs_cms_site_add:
    pattern:  /site/add
    defaults: { _controller: HostkitAdminBundle:CMS\Site:add }

hostkit_xs_cms_site_modify:
    pattern:  /site/modify/{id}
    defaults: { _controller: HostkitAdminBundle:CMS\Site:modify }

hostkit_xs_cms_site_delete:
    pattern:  /site/delete/{siteId}
    defaults: { _controller: HostkitAdminBundle:CMS\Site:delete }