parameters:
#    hostkit_setup.example.class: Hostkit\SetupBundle\Example

services:
#    hostkit_setup.example:
#        class: %hostkit_setup.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
