hostkit_xs_clients_overview:
    pattern:  /clients
    defaults: { _controller: HostkitAdminBundle:Clients\Default:index }

hostkit_xs_clients_write_email:
    pattern:  /clients/email/{clientId}
    defaults: { _controller: HostkitAdminBundle:Clients\Default:writeEmail }

hostkit_xs_client_detail:
    pattern:  /client/detail/{clientId}
    defaults: { _controller: HostkitAdminBundle:Clients\Default:detail }

hostkit_xs_client_invoice:
    pattern:  /client/invoice/{clientId}/{orderId}
    defaults: { _controller: HostkitAdminBundle:Clients\Default:showInvoice }

hostkit_xs_client_change_order_status:
    pattern:  /client/orderstatus/{clientId}/{orderId}
    defaults: { _controller: HostkitAdminBundle:Clients\Default:changeOrderStatus }