parameters:
#    hostkit_xs_email.example.class: Hostkit\EmailBundle\Example

services:
#    hostkit_xs_email.example:
#        class: %hostkit_xs_email.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    hostkit.twig.email_extension:
        class: Hostkit\EmailBundle\Twig\EmailExtension
        tags:
            - { name: twig.extension }