hostkit_client_homepage:
    pattern:  /dashboard/{error}
    defaults: { _controller: HostkitClientBundle:Default:dashboard, error:0 }

hostkit_client_settings:
    pattern:  /settings/{userId}
    defaults: { _controller: HostkitClientBundle:Default:settings }

_hosting:
    resource: "@HostkitClientBundle/Resources/config/hosting/routing.yml"

_email:
    resource: "@HostkitClientBundle/Resources/config/email/routing.yml"

_files:
    resource: "@HostkitClientBundle/Resources/config/files/routing.yml"

_domains:
    resource: "@HostkitClientBundle/Resources/config/domains/routing.yml"

_domainshosting:
    resource: "@HostkitClientBundle/Resources/config/domainshosting/routing.yml"

_databases:
    resource: "@HostkitClientBundle/Resources/config/databases/routing.yml"

_statistics:
    resource: "@HostkitClientBundle/Resources/config/statistics/routing.yml"

_reseller:
    resource: "@HostkitClientBundle/Resources/config/reseller/routing.yml"

_support:
    resource: "@HostkitClientBundle/Resources/config/support/routing.yml"

_invoice:
    resource: "@HostkitClientBundle/Resources/config/invoice/routing.yml"