parameters:
#    hostkit_client.example.class: Hostkit\ClientBundle\Example

services:
#    hostkit_client.example:
#        class: %hostkit_client.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
