hostkit_client_subdomains:
    pattern:  /subdomains
    defaults: { _controller: HostkitClientBundle:DomainHosting:subdomains }

hostkit_client_addondomains:
    pattern:  /addondomains
    defaults: { _controller: HostkitClientBundle:DomainHosting:addondomains }

hostkit_client_redirects:
    pattern:  /redirects
    defaults: { _controller: HostkitClientBundle:DomainHosting:redirects }

hostkit_client_dns:
    pattern:  /dns
    defaults: { _controller: HostkitClientBundle:DomainHosting:dns }