hostkit_client_email_list:
    pattern:  /email_list/{message}
    defaults: { _controller: HostkitClientBundle:Email:list, message: 0 }

hostkit_client_email_forwarders:
    pattern:  /email_forwards
    defaults: { _controller: HostkitClientBundle:Email:forwards }

hostkit_client_email_mxs:
    pattern:  /email_mxs
    defaults: { _controller: HostkitClientBundle:Email:mxs }

hostkit_client_email_filter:
    pattern:  /email_filter
    defaults: { _controller: HostkitClientBundle:Email:filter }

hostkit_client_email_del:
    pattern:  /email_del/{email}/
    defaults: { _controller: HostkitClientBundle:Email:delete }
